#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

bspc config border_width         1
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Google-chrome desktop='^1'
bspc rule -a discord desktop='^4' 
bspc rule -a firefox desktop='^5' 

${HOME}/.fehbg
compton &
/usr/bin/numlockx on
${HOME}/.config/polybar/launch.sh --shapes
xsetroot -cursor_name left_ptr &
xset s off -dpms
pactl set-default-sink alsa_output.usb-C-Media_Electronics_Inc._USB_Audio_Device-00.analog-stereo
